let TOTAL_OBSTACLES_COUNT = 30,
    VISIBLE_OBSTACLES_COUNT = 5,
    INTERVAL_SWITCH_ACTIVE_OBSTACLES = 6,
    TOTAL_QUESTIONS_COUNT = 5,
    MAZE_START_COORDS = 50,
    MAZE_END_COORDS = 700,
    HERO_DEFAULT_X = 65,
    HERO_DEFAULT_Y = 65;