let baseUrl = "https://baas.kinvey.com";
let appKey = "kid_HkuKRPKR";
let appSecret = "0fc10c7fcc434c5bb2ace8ec45a467ce";
let guest = "";
let requestUrl = baseUrl + "/appdata/" + appKey + "/players";
let authService = new AuthorizationService(baseUrl, appKey, appSecret, guest);
authService.initAuthorizationType("Kinvey");
let requester = new Requester(authService);
let data = requester.get(requestUrl);
console.log(data);
